spring:
  application:
    name: TradingApp
  data:
    mongodb:
      uri: mongodb+srv://vijaysingh3225:koMTTJy40P6fFZwS@marketstackdb.hb8bt.mongodb.net/MarketStack?retryWrites=true&w=majority
  profiles:
    active: default

  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Peanuts9
    key-store-type: PKCS12
    key-alias: myapp

api:
  closed-trade:
    base-url: /api/v1/closedTrades
    collection: Trade-Closed
  open-trade:
    base-url: /api/v1/openTrades
    collection: Trade-Open