spring:
  application:
    name: TradingApp
  data:
    mongodb:
      uri: mongodb+srv://vijaysingh3225:koMTTJy40P6fFZwS@marketstackdb.hb8bt.mongodb.net/MarketStack?retryWrites=true&w=majority
  profiles:
    active: default

api:
  closed-trade:
    base-url: /api/v1/closedTrades
    collection: Trade-Closed
  open-trade:
    base-url: /api/v1/openTrades
    collection: Trade-Open

